title: Thomas Höllt
baseurl: /
url: "https://www.thomashollt.com"
asset_url: /assets/

twitter: thomashollt
github: thoellt
email: t.hollt-1@tudelft.nl

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: _sass

collections:
  persons:
    output: false
    permalink: /persons/:path/
  publications:
    output: true
    permalink: /publications/:path/
  courses:
    output: true
    permalink: /teaching/:path/

exclude: [".git", ".github", ".gitignore", "Gemfile", "LICENSE", "README.md"]