title: Thomas Höllt
baseurl: /
url: "https://www.thomashollt.com"
asset_url: /assets/
document_url: https://raw.githubusercontent.com/thoellt/publications/main/

twitter: thomashollt
mastodon: thomashollt
mastodoninstance: vis.social
github: thoellt
email: t.hollt-1@tudelft.nl

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: _sass

collections:
  persons:
    output: false
    permalink: /persons/:path/
  publications:
    output: true
    permalink: /publications/:path/
  courses:
    output: true
    permalink: /teaching/:path/
  profiles:
    output: false
    permalink: /profiles/:path/
  awards:
    output: false
    permalink: /awards/:path/
  activities:
    output: false
    permalink: /activities/:path/
  teaching:
    output: false
    permalink: /teaching/:path/

exclude: [".git", ".github", ".gitignore", "Gemfile", "LICENSE", "README.md"]